///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Crucumber_StackOverflow
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Crucumber_StackOverflowRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("3fedc32a-0824-4373-9f7d-2580637d7209")]
    public partial class Crucumber_StackOverflowRepository : RepoGenBaseFolder
    {
        static Crucumber_StackOverflowRepository instance = new Crucumber_StackOverflowRepository();
        Crucumber_StackOverflowRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Crucumber_StackOverflowRepositoryFolders.OnlineCoursesAnytimeAnywhereUdeAppFolder _onlinecoursesanytimeanywhereude;

        /// <summary>
        /// Gets the singleton class instance representing the Crucumber_StackOverflowRepository element repository.
        /// </summary>
        [RepositoryFolder("3fedc32a-0824-4373-9f7d-2580637d7209")]
        public static Crucumber_StackOverflowRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Crucumber_StackOverflowRepository() 
            : base("Crucumber_StackOverflowRepository", "/", null, 0, false, "3fedc32a-0824-4373-9f7d-2580637d7209", ".\\RepositoryImages\\Crucumber_StackOverflowRepository3fedc32a.rximgres")
        {
            _applicationundertest = new Crucumber_StackOverflowRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _onlinecoursesanytimeanywhereude = new Crucumber_StackOverflowRepositoryFolders.OnlineCoursesAnytimeAnywhereUdeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3fedc32a-0824-4373-9f7d-2580637d7209")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("93c7ffdf-4f90-4691-b673-c05f8ef32f52")]
        public virtual Crucumber_StackOverflowRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The OnlineCoursesAnytimeAnywhereUde folder.
        /// </summary>
        [RepositoryFolder("c89a036d-eb7b-41d9-b8f8-80a4b47597a6")]
        public virtual Crucumber_StackOverflowRepositoryFolders.OnlineCoursesAnytimeAnywhereUdeAppFolder OnlineCoursesAnytimeAnywhereUde
        {
            get { return _onlinecoursesanytimeanywhereude; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class Crucumber_StackOverflowRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("93c7ffdf-4f90-4691-b673-c05f8ef32f52")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _oltagsecondaryjssecondarytopbarlinkInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _submitbuttonInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='stackoverflow.com']", parentFolder, 30000, null, true, "93c7ffdf-4f90-4691-b673-c05f8ef32f52", "")
            {
                _oltagsecondaryjssecondarytopbarlinkInfo = new RepoItemInfo(this, "OlTagSecondaryJsSecondaryTopbarLink", "?/?/header/?/?/ol", 30000, null, "ab1aa9c1-07c5-452d-9a95-71eb607071bd");
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", 30000, null, "2de9bbb7-184d-4a4b-8857-798e71a2e952");
                _submitbuttonInfo = new RepoItemInfo(this, "SubmitButton", ".//button[#'submit-button']", 30000, null, "0cd79c4d-a24c-4be9-a969-1aa52e537ae5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("93c7ffdf-4f90-4691-b673-c05f8ef32f52")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("93c7ffdf-4f90-4691-b673-c05f8ef32f52")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OlTagSecondaryJsSecondaryTopbarLink item.
            /// </summary>
            [RepositoryItem("ab1aa9c1-07c5-452d-9a95-71eb607071bd")]
            public virtual Ranorex.OlTag OlTagSecondaryJsSecondaryTopbarLink
            {
                get
                {
                    return _oltagsecondaryjssecondarytopbarlinkInfo.CreateAdapter<Ranorex.OlTag>(true);
                }
            }

            /// <summary>
            /// The OlTagSecondaryJsSecondaryTopbarLink item info.
            /// </summary>
            [RepositoryItemInfo("ab1aa9c1-07c5-452d-9a95-71eb607071bd")]
            public virtual RepoItemInfo OlTagSecondaryJsSecondaryTopbarLinkInfo
            {
                get
                {
                    return _oltagsecondaryjssecondarytopbarlinkInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("2de9bbb7-184d-4a4b-8857-798e71a2e952")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("2de9bbb7-184d-4a4b-8857-798e71a2e952")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The SubmitButton item.
            /// </summary>
            [RepositoryItem("0cd79c4d-a24c-4be9-a969-1aa52e537ae5")]
            public virtual Ranorex.ButtonTag SubmitButton
            {
                get
                {
                    return _submitbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("0cd79c4d-a24c-4be9-a969-1aa52e537ae5")]
            public virtual RepoItemInfo SubmitButtonInfo
            {
                get
                {
                    return _submitbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The OnlineCoursesAnytimeAnywhereUdeAppFolder folder.
        /// </summary>
        [RepositoryFolder("c89a036d-eb7b-41d9-b8f8-80a4b47597a6")]
        public partial class OnlineCoursesAnytimeAnywhereUdeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _paneInfo;
            RepoItemInfo _pane1Info;

            /// <summary>
            /// Creates a new OnlineCoursesAnytimeAnywhereUde  folder.
            /// </summary>
            public OnlineCoursesAnytimeAnywhereUdeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OnlineCoursesAnytimeAnywhereUde", "/form[@title~'^Online\\ Courses\\ -\\ Anytime,']", parentFolder, 30000, null, true, "c89a036d-eb7b-41d9-b8f8-80a4b47597a6", "")
            {
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename~'^Online\\ Courses\\ -\\ Anytime,']/container/container[1]", 30000, null, "303e8569-64f1-45a7-af37-1c53a7722cd3");
                _pane1Info = new RepoItemInfo(this, "Pane1", "container[@accessiblename='New Tab - Google Chrome']/container[@accessiblename='Google Chrome']/container[1]", 30000, null, "f7a254ae-5ef1-4523-a4d8-7de98f553718");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c89a036d-eb7b-41d9-b8f8-80a4b47597a6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c89a036d-eb7b-41d9-b8f8-80a4b47597a6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("303e8569-64f1-45a7-af37-1c53a7722cd3")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("303e8569-64f1-45a7-af37-1c53a7722cd3")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }

            /// <summary>
            /// The Pane1 item.
            /// </summary>
            [RepositoryItem("f7a254ae-5ef1-4523-a4d8-7de98f553718")]
            public virtual Ranorex.Container Pane1
            {
                get
                {
                    return _pane1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane1 item info.
            /// </summary>
            [RepositoryItemInfo("f7a254ae-5ef1-4523-a4d8-7de98f553718")]
            public virtual RepoItemInfo Pane1Info
            {
                get
                {
                    return _pane1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}