///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Crucumber_StackOverflow
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("33db149c-ed39-47da-a1be-1725d17e8154", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Crucumber_StackOverflowRepository repository.
        /// </summary>
        public static Crucumber_StackOverflowRepository repo = Crucumber_StackOverflowRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineCoursesAnytimeAnywhereUde.Pane' at 336;36.", repo.OnlineCoursesAnytimeAnywhereUde.PaneInfo, new RecordItemIndex(0));
            repo.OnlineCoursesAnytimeAnywhereUde.Pane.Click("336;36");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'stack'.", new RecordItemIndex(1));
            Keyboard.Press("stack");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OnlineCoursesAnytimeAnywhereUde.Pane1' at 450;78.", repo.OnlineCoursesAnytimeAnywhereUde.Pane1Info, new RecordItemIndex(2));
            repo.OnlineCoursesAnytimeAnywhereUde.Pane1.Click("450;78");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(3));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.OlTagSecondaryJsSecondaryTopbarLink' at 392;25.", repo.ApplicationUnderTest.OlTagSecondaryJsSecondaryTopbarLinkInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.OlTagSecondaryJsSecondaryTopbarLink.Click("392;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Email' at 109;29.", repo.ApplicationUnderTest.EmailInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Email.Click("109;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'papas{Tab}' with focus on 'ApplicationUnderTest.Email'.", repo.ApplicationUnderTest.EmailInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Email.PressKeys("papas{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'queso'.", new RecordItemIndex(7));
            Keyboard.Press("queso");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SubmitButton' at 58;25.", repo.ApplicationUnderTest.SubmitButtonInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.SubmitButton.Click("58;25");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
